local curr_internal_conf = require("anysphere.config.internal").current
return {
  common = require("anysphere.groups.common").get_colors(curr_internal_conf),
  diff = require("anysphere.groups.diff").get_colors(curr_internal_conf),
  cmp = require("anysphere.groups.cmp").get_colors(curr_internal_conf),
  blink = require("anysphere.groups.blink").get_colors(curr_internal_conf),
  lsp_native = require("anysphere.groups.lsp-native").get_colors(curr_internal_conf),
  lsp_plugin = require("anysphere.groups.lsp-plugin").get_colors(curr_internal_conf),
  gitsigns = require("anysphere.groups.gitsigns").get_colors(curr_internal_conf),
  neotest = require("anysphere.groups.neotest").get_colors(curr_internal_conf),
  mini = require("anysphere.groups.mini").get_colors(curr_internal_conf),
  neotree = require("anysphere.groups.neotree").get_colors(curr_internal_conf),
  syntax = require("anysphere.groups.syntax").get_colors(curr_internal_conf),
  telescope = require("anysphere.groups.telescope").get_colors(curr_internal_conf),
  treesitter = require("anysphere.groups.treesitter").get_colors(curr_internal_conf),
  dashboard = require("anysphere.groups.dashboard").get_colors(curr_internal_conf),
  snacks_picker = require("anysphere.groups.snacks-picker").get_colors(curr_internal_conf),
  snacks_input = require("anysphere.groups.snacks-input").get_colors(curr_internal_conf),
  snacks_indent = require("anysphere.groups.snacks-indent").get_colors(curr_internal_conf),
  rainbow_delimiters = require("anysphere.groups.rainbow-delimiters").get_colors(curr_internal_conf),
  vim_better_whitespace = require("anysphere.groups.vim-better-whitespace").get_colors(curr_internal_conf),
}
